### PR TITLE
[PAL] Decoulping SGX PAL initialization and app execution.

### PR DESCRIPTION
**Pull request by yfmai**
Various app that signed by authenticated user could re-execute in one
LibOS process.

Signed-off-by: Michael Y. Mai <yfmai@linux.alibaba.com>

## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [X] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 
Process initialization is decoupled, SGX PAL could initialize once and execute various app binary any times now.

### CODE REVIEW

**Comment by yamahata** [comment]
Hi. This PR lacks the usage of it and the patch seems incomplete.
Can you please explain what it does and why this is useful?

**Comment by yfmai** [comment]
Sure. This patch was discussed with Gordon, we expect the code would get well-reviewed. If there's any inappropriate please let me know.
Based on pal-sgx executable, this patch generates a stand-alone library named liberpal-gsgx.so under directory Pal/src/host/Linux-SGX. The library exposes 5 interfaces to support to be called from/in another process which are pal_version(), pal_init(), pal_exec(), pal_kill() and pal_report().
The original execution model that a LibOS and app binary will be initialized and executed once, will be loading the LibOS repeatedly while the app is re-executed, which has a notable latency on LibOS loading. A new feature that a LibOS could be initialized only once and apps could be executed much time in the same process are purposed by this patch, of course, apps must be signed by a valid signing key which the public key (or the certificate) has specified in the manifest.
The code was tested by local gtest cases, new library liberpal-gsgx.so was loaded dynamically by dlopen() and initialized by pal_init(), in other cases, pal_exec() was called 3 times to load different native apps: helloworld, time, then helloworld, all apps do correctly executed.

Regards,
Michael

**Comment by yfmai** [comment]
Update with some implementation for remove dependency of glibc:
- [x] setjmp/longjmp integrated into PAL.
- [x] removed the global variable `environ`.
- [x] jmp_buf placed into `tcb` for each thread, `dlopen` is removed.

**Comment by yfmai** [comment]
Fix build issue of 'run_pal_loader'.

**Pull request merged**
